// This file is generated by Slice Machine. Update with care!

import FullWidth from './FullWidth';
import TwoColumns from './TwoColumns';

export {
	FullWidth,
	TwoColumns,
};

export const components = {
	full_width: FullWidth,
	two_columns: TwoColumns,
};
